version: "3.9"

services:
  db:
    image: postgres:15
    container_name: grimoire-postgres
    restart: unless-stopped
    ports:
      - "${POSTGRES_PORT}:${POSTGRES_PORT}"
    environment:
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
      POSTGRES_DB: ${POSTGRES_DB}
    volumes:
      - grimoire_pgdata:/var/lib/postgresql/data

volumes:
  grimoire_pgdata:
